"""Judge: pick the winner among candidates that cleared every gate, then write the PR text."""
from .. import llm


def pick(verdicts):
    ok = [v for v in verdicts if v.passed]
    return min(ok, key=lambda v: (v.diff_lines, len(v.files), v.index)) if ok else None


def _summary(issue, winner):
    try:
        text = llm.chat([{"role": "system", "content": "Write 2-3 plain sentences: the root cause and "
                          "what the patch changes. No headings."},
                         {"role": "user", "content": f"ROLE: summary\nISSUE:\n{issue}\n\nDIFF:\n{winner.diff}"}],
                        temperature=0.2, max_tokens=300)
        return text.strip()
    except Exception:
        return "See the diff below."


def write_pr(issue, winner, verdicts, exploit_before):
    rows = "\n".join(
        f"| {v.index} | {v.strategy} | {'PASS' if v.passed else 'fail'} | {v.reason} |"
        for v in sorted(verdicts, key=lambda v: v.index))
    return f"""## Security fix: {issue.strip().splitlines()[0]}

{_summary(issue, winner)}

### Evidence
- Reproduction test failed on the original code, then passes with this patch.
- Full existing test suite is green with this patch.
- Diff size: {winner.diff_lines} changed lines in {', '.join(winner.files)}.

<details><summary>Reproduction test output before the patch</summary>

```
{exploit_before[-1200:].strip()}
```
</details>

### Candidate tournament ({len(verdicts)} candidates, {sum(v.passed for v in verdicts)} verified)
| # | Strategy | Result | Why |
|---|---|---|---|
{rows}

### Diff
```diff
{winner.diff.rstrip()}
```

_Generated by PatchArena. Human review required before merge._
"""


def write_needs_human(issue, verdicts, reason):
    rows = "\n".join(f"- #{v.index}: {v.reason}" for v in sorted(verdicts, key=lambda v: v.index))
    return f"## Needs human: {issue.strip().splitlines()[0]}\n\n{reason}\n\n{rows}\n"
